import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";
import { Public_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/general/themeProvider";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${publicSans.variable} ${publicSans.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>

          {children}
          <Toaster closeButton richColors />

        </ThemeProvider>

      </body>
    </html>
  );
}
